split API from implementation
eclipse-ee4j/jaf pull request #71
Opened 2021-04-10 10:43 UTC by aserkes

split API from implementation
Signed-off-by: aserkes <andrii.serkes@oracle.com>

2021-04-29 14:04 UTC, lukasj reviewed
In general - I like this! I will have some comments as I go through this. First are:
* new files should have only 2021 in cp year
* implementation should also contain module-info
* there needs to be better (and/or properly documented) way to handle missing implementation - `ServiceLoader.load(MailcapRegistryProvider.class).iterator().next().getDefault()` may throw an exception if there is no implementation available

2021-05-03 10:13 UTC, lukasj requested changes
* new interfaces in `jakarta.activation.spi` package require javadoc
* consider renaming `getDefault` methods to `getEmpty` (or something more appropriate)

2021-05-26 05:47 UTC, lukasj approved these changes
I think this is OK. We can fine-tune it later. Just rebase it, so it can be merged. Thanks!

2021-05-26 05:48 UTC, lukasj commented on activation/src/main/java/jakarta/activation/MimeTypeRegistry.java
> +        else
`else` is redundant here

2021-05-26 05:49 UTC, lukasj commented on activation/src/main/java/jakarta/activation/MimetypesFileTypeMap.java
> +				if (LogSupport.isLoggable()) {
the spaces here look like `tabs`. Make sure real space characters are used (no `tabs`)

2021-05-26 05:51 UTC, lukasj commented on activation/src/main/java/jakarta/activation/MimetypesFileTypeMap.java
>  	    //	e.printStackTrace();
do not swallow exceptions. Either remove the catch or move it to the next one so it is at least logged

2021-05-26 05:58 UTC, lukasj commented on activation/src/main/java/jakarta/activation/spi/package.html
> +<HTML>
it's better to use `package-info.java` files instead of html

2021-05-26 14:06 UTC, aserkes commented
All fixes are done. Code is ready to merge.

2021-05-26 14:54 UTC, merged